version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mightyBroccoli
  ignore:
  - dependency-name: slixmpp
    versions:
    - 1.6.0
